name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2. Instala Python
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      # 3. Instala dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Lint com pylint (ou flake8, se preferir)
      - name: Lint com Pylint
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

      # 5. Executar testes com pytest
      - name: Testes com Pytest
        run: pytest
